apiVersion: v1
kind: ConfigMap
metadata:
    name: backend-configmap
data:
    mongodb_host: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mern-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: kube-mern-server:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                  env:
                      - name: MONGODB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: backend-configmap
                                key: mongodb_host
---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: server
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
