apiVersion: v1
kind: ConfigMap
metadata:
    name: backend-configmap
data:
    database_url: mongodb-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mern-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: kube-mern-server:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                  env:
                  - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                    valueFrom:
                      secretKeyRef:
                          name: mongodb-secret
                          key: mongo-root-username
                  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                    valueFrom: 
                      secretKeyRef:
                          name: mongodb-secret
                          key: mongo-root-password
                  - name: ME_CONFIG_MONGODB_SERVER
                    valueFrom: 
                      configMapKeyRef:
                          name: backend-configmap
                          key: database_url

---
apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: server
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080




