apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-configmap
data:
    server_host: backend-service
    server_port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mern-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            labels:
                app: client
        spec:
            containers:
                - name: client
                  image: kube-mern-client:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3000
                  env:
                      - name: SERVER_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: frontend-configmap
                                key: server_host
                      - name: SERVER_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: frontend-configmap
                                key: server_port
---
apiVersion: v1
kind: Service
metadata:
    name: front-service
spec:
    selector:
        app: client
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
          nodePort: 31001