# We configured the PVC to configure the storage to keep the configuration information.
replicas: 1

service:
    type: NodePort
    nodePort: 30001

persistence:
    type: pvc
    enabled: true
    accessModes:
        - ReadWriteOnce
    size: 10Gi
    finalizers:
        - kubernetes.io/pvc-protection

adminUser: admin
adminPassword: OntherMontoring
